### ISSUE TITLE
Translation-reader failing in ocis pipeline

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/translation-sync#67]
## Description
Failed in `translation-reader` step pipeline.

```
make[1]: Entering directory '/drone/src/ocis/services/activitylog'
go-xgettext -o ./pkg/service/l10n/activitylog.pot --keyword=l10n.Template -s pkg/service/response.go
panic: unknown type: _someField

goroutine 1 [running]:
main.constructValue({0x4fcc80?, 0xc00007aa20?})
	/drone/src/go-xgettext/main.go:116 +0x179
main.inspectNodeForTranslations(0xc000159990?, 0x4e4857?, {0x53aad0, 0xc000110500})
	/drone/src/go-xgettext/main.go:164 +0x3d6
main.processSingleGoSource.func1({0x53aad0?, 0xc000110500?})
	/drone/src/go-xgettext/main.go:236 +0x37
go/ast.inspector.Visit(0xc0000113c8, {0x53aad0?, 0xc000110500?})
	/usr/local/go/src/go/ast/walk.go:386 +0x31
go/ast.Walk({0x53a888?, 0xc0000113c8?}, {0x53aad0?, 0xc000110500?})
	/usr/local/go/src/go/ast/walk.go:51 +0x62
go/ast.walkExprList({0x53a888, 0xc0000113c8}, {0xc0000787b0?, 0x1, 0xc000110080?})
	/usr/local/go/src/go/ast/walk.go:26 +0x91
go/ast.Walk({0x53a888?, 0xc0000113c8?}, {0x53b200?, 0xc00007c500?})
	/usr/local/go/src/go/ast/walk.go:318 +0x77f
go/ast.Walk({0x53a888?, 0xc0000113c8?}, {0x53adc8?, 0xc000110680?})
	/usr/local/go/src/go/ast/walk.go:344 +0x233c
go/ast.walkDeclList({0x53a888, 0xc0000113c8}, {0xc000136200?, 0x12, 0x2352?})
	/usr/local/go/src/go/ast/walk.go:38 +0x91
go/ast.Walk({0x53a888?, 0xc0000113c8?}, {0x53ad00?, 0xc000032780?})
	/usr/local/go/src/go/ast/walk.go:366 +0xdea
go/ast.Inspect(...)
	/usr/local/go/src/go/ast/walk.go:397
main.processSingleGoSource(0xc000110080, {0x7ffc8f9d935e, 0x17})
	/drone/src/go-xgettext/main.go:235 +0xe5
main.processFiles({0xc000014250, 0x1, 0xc0000141e0?})
	/drone/src/go-xgettext/main.go:215 +0xae
main.main()
	/drone/src/go-xgettext/main.go:344 +0xcd
make[1]: *** [Makefile:47: l10n-read] Error 2
make[1]: Leaving directory '/drone/src/ocis/services/activitylog'
make: *** [Makefile:308: l10n-read] Error 1
```
Build:
https://drone.owncloud.com/owncloud/translation-sync/3487/35/4

**Comment by DeepDiver1975** [comment]
related change: https://github.com/owncloud/ocis/commit/1a23ea5a788cd319ff1990a7be2f86ff4b701d10#diff-7fadd799139736b692eafbd8020fd9f62793ddf8a59379eec1bd144482e58cd0

**Comment by saw-jan** [comment]
Something to fix in ocis?

**Comment by saw-jan** [comment]
Something to fix in ocis?

CC @2403905

**Comment by saw-jan** [comment]
@micbar @2403905 `make l10n-read` started to fail. Should this issue be moved to oCIS repo?

**Comment by saw-jan** [comment]
Fix: https://github.com/owncloud/ocis/pull/10175

**Comment by saw-jan** [comment]
CI is happy. Closing as fixed
https://drone.owncloud.com/owncloud/translation-sync/3493/35/4
